version: "3"
services:
 nodeapp:
  container_name: express-node-production
  build:
    context: .
    target: production
    #---
    # args:
    # - NODE_ENV=production
    #---
  environment: 
     - NODE_ENV=prodection
  command: npm run  start
