version: "3"
services:
 nodeapp:
 
   build:
    context: .
    target: development
    # ---
    # args:
    # - NODE_ENV=development
     # ---
   volumes:
     - ./volums:/app/volums:ro
    
   environment: 
     - NODE_ENV=development 
   command: npm run start-dev