version: "3"
services:
 nodeapp:
   ports:
     - "5000:5000"
   env_file:
    - ./.env 
   depends_on:
    - mongo
    - redis

 mongo:
    image: mongo
    container_name: mongo-container
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example 

 mongo-express:
    container_name: mongo-express-container
    image: mongo-express
    restart: always
    ports:
      - 80:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
    - mongo

 redis:
  container_name: redis-container
  image: redis
  

 nginx:
  container_name: nginx-container
  image: nginx:stable-alpine
  ports:
   - "8080:80"
   - "888:888"
  depends_on:
    - nodeapp
    - mongo
    - mongo-express
  volumes:
   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  mongo-db:     
      
 
