version: "3"
services:
 nodeapp:
   container_name: express-node-app-container
   build: .
   volumes:
     - ./volums:/app/volums:ro
    
   ports:
     - "5000:5000"
   # ---
   #environment: 
    #- PORT=5000 
    #- MYNAME=mostafa
   #---
   env_file:
    - ./.env